# Generated by Django 4.0.4 on 2022-06-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orginization',
            name='is_nonprofit',
            field=models.BooleanField(default=False, verbose_name='Non-Profit'),
        ),
    ]
