# Generated by Django 4.0.4 on 2022-06-08 04:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tithe_app', '__first__'),
        ('org_app', '0002_alter_orginization_is_nonprofit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orginization',
            new_name='Organization',
        ),
    ]
